site_name: Project Management Toolkit
theme:
  name: material
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: blue grey
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tracking
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.expand


plugins:
  - search
  - awesome-pages:
      sort_type: natural
      order_by: title
      collapse_single_pages: true
  # - table-reader
